auth/urls.py
from django.conf.urls import patterns, include, url
from auth import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^logout/$', views.logout_view),
)

nhcp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('auth.urls')),
    url(r'^', include('seals.urls')),
)

seals/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required
from seals.views import *
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', MapView.as_view(), name='map-view'),
    url(r'^new/$', login_required(CreateSealView.as_view()), name='new-seal-view'),
    url(r'^category/$', RegionView.as_view(), name='category-view'),
    url(r'^category/new/$', login_required(CreateCategoryView.as_view())),
    url(r'^category/(?P<pk>[\w-]+)/edit/$', login_required(UpdateCategoryView.as_view()), name='category-edit-view'),
    url(r'^category/(?P<pk>[\w-]+)/delete/$', login_required(CategoryDelete.as_view())),
    url(r'^category/(?P<pk>[\w-]+)/svg/$', login_required(UpdateSVG.as_view()), name='category-svg-view'),
    url(r'^(?P<pk>[\w-]+)/$', SealView.as_view(), name='seal-view'),
    url(r'^(?P<pk>[\w-]+)/edit/$', login_required(UpdateSealView.as_view()), name='seal-edit-view'),
    url(r'^(?P<pk>[\w-]+)/delete/$', login_required(SealDelete.as_view()), name='seal-delete-view'),
    url(r'^(?P<pk>[\w-]+)/seal-info/$', login_required(CreateSealInfoView.as_view()), name='seal-info-view'),
    url(r'^(?P<pk>[\w-]+)/create-property/$', login_required(CreateSealProperty.as_view()), name='seal-prpty-view'),

    url(r'^sample$', TemplateView.as_view(template_name="sample.html")),
)

seals/models.py
from django.db import models
from geoposition.fields import GeopositionField


class Region(models.Model):
    name = models.CharField(max_length=50, null=False)
    name_fil = models.CharField(max_length=50, null=False, blank=False)
    svg = models.CharField(max_length=2000, null=False, blank=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class Province(models.Model):
    name = models.CharField(max_length=50, null=False)
    name_fil = models.CharField(max_length=50, null=False, blank=False)
    region = models.ForeignKey(Region)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class LGU(models.Model):
    image = models.ImageField(
        upload_to='images/seals/', default='images/seals/no-img.jpg')
    name = models.CharField(max_length=50, null=False)
    name_fil = models.CharField(max_length=50, null=False, blank=False)
    image_thumbnail = models.ImageField(
        upload_to='images/seals/thumbnail/', default='images/seals/thumbnail/no-img.jpg')
    description = models.CharField(max_length=500, null=False, blank=False)
    description_fil = models.CharField(max_length=500, null=False, blank=False)
    province = models.ForeignKey(Province)
    location = GeopositionField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class SealInfo(models.Model):
    name = models.CharField(max_length=50, null=False)
    name_fil = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=500, null=False, blank=False)
    description_fil = models.CharField(max_length=500, null=False, blank=False)
    seal = models.ForeignKey(LGU)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class SealProperty(models.Model):
    name = models.CharField(max_length=50, null=False)
    name_fil = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=500, null=False, blank=False)
    description_fil = models.CharField(max_length=500, null=False, blank=False)
    svg = models.CharField(max_length=2000, null=False, blank=False)
    seal = models.ForeignKey(LGU)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

seals/forms.py
from django import forms
from seals.models import Region, Province, LGU, SealInfo, SealProperty

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field


class CategoryCreationForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-1'
    helper.field_class = 'col-lg-11'
    helper.form_tag = False
    helper.layout = Layout(
        Field('name', wrapper_class='row'),
    )

    name = forms.CharField(required=True)

    class Meta:
        model = Region
        fields = ('name',)


class EditSVGForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-10'
    helper.form_tag = False
    helper.layout = Layout(
        Field('name_fil', wrapper_class='row'),
    )

    name_fil = forms.CharField(required=False, label='Name in Filipino')
    svg = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Region
        fields = ('name_fil', 'svg')


class SealCreationForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-10'
    helper.form_tag = False
    helper.layout = Layout(
        Field('image', wrapper_class='row'),
        Field('name', wrapper_class='row'),
        Field('name_fil', wrapper_class='row'),
        Field('description', wrapper_class='row'),
        Field('description_fil', wrapper_class='row'),
        Field('province', wrapper_class='row'),
    )

    image = forms.ImageField()
    name = forms.CharField(required=True)
    name_fil = forms.CharField(required=False, label='Name in Filipino')
    description = forms.CharField(widget=forms.Textarea, required=False)
    description_fil = forms.CharField(
        widget=forms.Textarea, label='Description in Filipino', required=False)
    province = forms.ModelChoiceField(
        Province.objects.all(), label='Official Seal of(Subcategory)')

    class Meta:
        model = LGU
        fields = ('image', 'name', 'name_fil', 'description',
                  'description_fil', 'province', 'location')


class SealInfoForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-10'
    helper.form_tag = False
    helper.layout = Layout(
        Field('name', wrapper_class='row'),
        Field('name_fil', wrapper_class='row'),
        Field('description', wrapper_class='row'),
        Field('description_fil', wrapper_class='row'),
    )

    name = forms.CharField(required=True)
    name_fil = forms.CharField(required=False, label='Name in Filipino')
    description = forms.CharField(widget=forms.Textarea, required=False)
    description_fil = forms.CharField(
        widget=forms.Textarea, label='Description in Filipino', required=False)

    class Meta:
        model = SealInfo
        fields = ('name', 'name_fil', 'description', 'description_fil')


class SealPropertyForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-2'
    helper.field_class = 'col-lg-10'
    helper.form_tag = False
    helper.layout = Layout(
        Field('name', wrapper_class='row'),
        Field('name_fil', wrapper_class='row'),
        Field('description', wrapper_class='row'),
        Field('description_fil', wrapper_class='row'),
    )

    name = forms.CharField(required=True)
    name_fil = forms.CharField(required=False, label='Name in Filipino')
    description = forms.CharField(widget=forms.Textarea, required=False)
    description_fil = forms.CharField(
        widget=forms.Textarea, label='Description in Filipino', required=False)
    svg = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = SealProperty
        fields = ('name', 'name_fil', 'description', 'description_fil', 'svg')

seals/views.py
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.utils import translation
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Region, Province, LGU, SealProperty
from .forms import CategoryCreationForm, EditSVGForm, SealCreationForm, SealInfoForm, SealPropertyForm


class MapView(ListView):
    queryset = LGU.objects.all().order_by('name')
    template_name = 'seals/map.html'

    def get_context_data(self, **kwargs):
        context = super(MapView, self).get_context_data(**kwargs)
        context['regions'] = Region.objects.all()
        context['provinces'] = Province.objects.all().order_by('name')
        return context


class RegionView(ListView):
    queryset = Region.objects.all().order_by('name')
    template_name = 'seals/region_list.html'

    def get_context_data(self, **kwargs):
        context = super(RegionView, self).get_context_data(**kwargs)
        return context


class CreateCategoryView(CreateView):
    template_name = 'seals/create_category.html'
    form_class = CategoryCreationForm
    success_url = reverse_lazy('map-view')

    def form_valid(self, form):
        if '_save' in self.request.POST:
            self.success_url = reverse_lazy('map-view')
        elif '_save_and_edit' in self.request.POST:
            self.success_url = reverse_lazy(
                'category-edit-view', kwargs={'pk': form.instance.name})
        return super(CreateCategoryView, self).form_valid(form)


class UpdateCategoryView(UpdateView):
    model = Region
    form_class = CategoryCreationForm
    template_name = 'seals/update_category.html'
    success_url = reverse_lazy('map-view')

    def get_object(self):
        name = self.kwargs['pk'].replace('-', ' ')
        return get_object_or_404(Region, name__iexact=name)

    def form_valid(self, form):
        if '_save' in self.request.POST:
            self.success_url = reverse_lazy('map-view')
        elif '_save_and_edit' in self.request.POST:
            self.success_url = reverse_lazy(
                'category-edit-view', kwargs={'pk': form.instance.name})
        return super(UpdateCategoryView, self).form_valid(form)


class CategoryDelete(DeleteView):
    model = Region
    template_name = 'seals/delete_category.html'
    success_url = reverse_lazy('category-view')

    def get_object(self):
        name = self.kwargs['pk'].replace('-', ' ')
        return get_object_or_404(Region, name__iexact=name)


class UpdateSVG(UpdateView):
    model = Region
    form_class = EditSVGForm
    template_name = 'seals/edit_svg.html'

    def get_object(self):
        name = self.kwargs['pk'].replace('-', ' ')
        return get_object_or_404(Region, name__iexact=name)

    def get_success_url(self):
        return reverse_lazy('category-svg-view', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        return super(UpdateSVG, self).form_valid(form)


class CreateSealView(CreateView):
    template_name = 'seals/create_seal.html'
    form_class = SealCreationForm
    success_url = reverse_lazy('map-view')

    def form_valid(self, form):
        return super(CreateSealView, self).form_valid(form)


class SealView(DetailView):
    template_name = 'seals/seal.html'

    def get_object(self):
        name = self.kwargs['pk'].replace('-', ' ')
        return get_object_or_404(LGU, name__iexact=name)

    def get_context_data(self, **kwargs):
        context = super(SealView, self).get_context_data(**kwargs)
        context['properties'] = SealProperty.objects.filter(seal=self.object)
        return context


class UpdateSealView(UpdateView):
    model = LGU
    form_class = SealCreationForm
    template_name = 'seals/update_seal.html'
    success_url = reverse_lazy('map-view')

    def get_object(self):
        name = self.kwargs['pk'].replace('-', ' ')
        return get_object_or_404(LGU, name__iexact=name)

    def get_success_url(self):
        return reverse_lazy('seal-edit-view', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        return super(UpdateSealView, self).form_valid(form)


class SealDelete(DeleteView):
    model = LGU
    template_name = 'seals/delete_seal.html'
    success_url = reverse_lazy('map-view')

    def get_object(self):
        name = self.kwargs['pk'].replace('-', ' ')
        return get_object_or_404(LGU, name__iexact=name)


class CreateSealInfoView(CreateView):
    template_name = 'seals/create_seal_info.html'
    form_class = SealInfoForm

    def get_success_url(self):
        return reverse_lazy('seal-view', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form, **kwargs):
        name = self.kwargs['pk'].replace('-', ' ')
        lgu = get_object_or_404(LGU, name__iexact=name)
        form.instance.seal = lgu
        return super(CreateSealInfoView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateSealInfoView, self).get_context_data(**kwargs)
        name = self.kwargs['pk'].replace('-', ' ')
        context['object'] = get_object_or_404(LGU, name__iexact=name)
        return context


class CreateSealProperty(CreateView):
    form_class = SealPropertyForm
    template_name = 'seals/create_seal_property.html'

    def get_context_data(self, **kwargs):
        context = super(CreateSealProperty, self).get_context_data(**kwargs)
        name = self.kwargs['pk'].replace('-', ' ')
        context['object'] = get_object_or_404(LGU, name__iexact=name)
        return context

    def get_success_url(self):
        return reverse_lazy('seal-view', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        name = self.kwargs['pk'].replace('-', ' ')
        form.instance.seal = get_object_or_404(LGU, name__iexact=name)
        return super(CreateSealProperty, self).form_valid(form)

templates/seals/create_category.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
        <form action="/category/new/" method="post" class="form segment">
            {% crispy form %}
            <input class="btn btn-success" type="submit" name="_save" value="Submit">
            <input class="btn btn-success" type="submit" name="_save_and_edit" value="Submit and edit">
            <a class="btn btn-primary" disabled="disabled">Edit SVG</a>
            <a class="btn btn-primary" href="/">Cancel</a>
        </form>
        <p>* If this category is part of the map, specify a name first and save it, then you'll get access to the edit SVG button. You'll then draw on the map the areas this region covers.</p>
    </div>

{% endblock %}

templates/seals/create_seal.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
        <form action="/new/" method="post" class="form segment">
            {{ form.media }}
            {% crispy form %}
            <input class="btn btn-success" type="submit" name="_save" value="Submit">
            <a class="btn btn-primary" href="/">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/seals/create_seal_info.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
        <form action="/{{ object.name|slugify }}/seal-info/" method="post" class="form segment">
            {% crispy form %}
            <input class="btn btn-success" type="submit" name="_save" value="Submit">
            <a class="btn btn-primary" href="/">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/seals/create_seal_property.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block js_up %}
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "js/jquery.svg.js" %}"></script>
    <script src="/static/js/modernizr-svg.js"></script>
    <script type="text/javascript">
        var drawNodes = [];
        var sketchpad = null;
        var polygon = null;
        $(function() {
            $('#svg-div').svg({onLoad: drawInitial});
            $('.clear-svg').on('click', function(e){
                drawNodes = [];
                polygon.remove();
                polygon = sketchpad.polygon(drawNodes, {fill: '#00BFFF', stroke: '#4169E1', strokeWidth: 1, opacity:0.5});
                $('#id_svg').val('');
            });
        });

        function drawInitial(svg) {
            sketchpad = svg;
            var surface = svg.image(0, 0, 500, 728, '{% static "media/" %}{{object.image}}');
            polygon = svg.polygon([],{fill: '#FFFFFF', stroke: '#FFFFFF', strokeWidth: 1, opacity:0.5});

            $(polygon).attr('points', '{{ object.svg }}');

            $(surface).click(function(){
                var offset = $('#svg-div').offset();
                offset.left -= document.documentElement.scrollLeft || document.body.scrollLeft;
                offset.top -= document.documentElement.scrollTop || document.body.scrollTop;

                var start = {X: event.clientX - offset.left, Y: event.clientY - offset.top};
                drawNodes.push([event.clientX - offset.left,event.clientY - offset.top]);
                polygon.remove();
                polygon = svg.polygon(drawNodes, {fill: '#FFFFFF', stroke: '#FFFFFF', strokeWidth: 1, opacity:0.5});
                $('#id_svg').val($(polygon).attr('points'));
                event.preventDefault();
            });
        }

    </script>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="col-sm-12">
            <div id="svg-div" style="width: 500px; height: 728px;">
            </div>
            <p class="lead">Click on the image to create the selected area.</p>
            <div class="btn-group">
                <button type="button" class="btn btn-danger clear-svg"><i class="fa fa-undo"></i> Clear</button>
            </div>
        </div>

        <form action="/{{ object.name }}/create-property/" method="post" class="form segment">
            {% crispy form %}
            <input class="btn btn-success" type="submit" name="_save" value="Submit">
            <a class="btn btn-primary" href="/{{ object.name }}/">Cancel</a>
        </form>
        <p>{{ form.errors }}</p>

    </div>
{% endblock %}

templates/seals/delete_category.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
        <form action="/category/{{ object.name|slugify }}/delete/" method="post" class="form segment">
            {% csrf_token %}
            <div class="alert alert-warning">
                    <h2>Deleting {{ object }}...</h2>
                    <p>
                        Are you sure you want to delete this item?
                        <strong>
                            Anything depending on this item will be deleted as well!
                        </strong>
                    </p>
            </div>
            <input class="btn btn-success" type="submit" name="confirm" value="Confirm">
            <a class="btn btn-primary" href="/category/">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/seals/delete_seal.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
        <form action="/{{ object.name|slugify }}/delete/" method="post" class="form segment">
            {% csrf_token %}
            <div class="alert alert-warning">
                    <h2>Deleting {{ object }}...</h2>
                    <p>
                        Are you sure you want to delete this item?
                        <strong>
                            Anything depending on this item will be deleted as well!
                        </strong>
                    </p>
            </div>
            <input class="btn btn-success" type="submit" name="confirm" value="Confirm">
            <a class="btn btn-primary" href="/">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/seals/edit_svg.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block js_up %}
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "js/jquery.svg.js" %}"></script>
    <script src="/static/js/modernizr-svg.js"></script>
    <script type="text/javascript">
        var drawNodes = [];
        var sketchpad = null;
        var polygon = null;
        $(function() {
            $('#svg-div').svg({onLoad: drawInitial});
            $('.clear-svg').on('click', function(e){
                drawNodes = [];
                polygon.remove();
                polygon = sketchpad.polygon(drawNodes, {fill: '#00BFFF', stroke: '#4169E1', strokeWidth: 1, opacity:0.5});
                $('#id_svg').val('');
            });
        });

        function drawInitial(svg) {
            sketchpad = svg;
            var surface = svg.image(0, 0, 500, 728, '{% static "images/philippine-map.jpg" %}');
            polygon = svg.polygon([],{fill: '#FFFFFF', stroke: '#FFFFFF', strokeWidth: 1, opacity:0.5});

            $(polygon).attr('points', '{{ object.svg }}');

            $(surface).click(function(){
                var offset = $('#svg-div').offset();
                offset.left -= document.documentElement.scrollLeft || document.body.scrollLeft;
                offset.top -= document.documentElement.scrollTop || document.body.scrollTop;

                var start = {X: event.clientX - offset.left, Y: event.clientY - offset.top};
                drawNodes.push([event.clientX - offset.left,event.clientY - offset.top]);
                polygon.remove();
                polygon = svg.polygon(drawNodes, {fill: '#FFFFFF', stroke: '#FFFFFF', strokeWidth: 1, opacity:0.5});
                $('#id_svg').val($(polygon).attr('points'));
                event.preventDefault();
            });
        }

    </script>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="col-sm-12">
            <div id="svg-div" style="width: 500px; height: 728px;">
            </div>
            <p class="lead">Click on the image to create the selected area.</p>
            <div class="btn-group">
                <button type="button" class="btn btn-danger clear-svg"><i class="fa fa-undo"></i> Clear</button>
            </div>
        </div>

        <form action="/category/{{ object.name }}/svg/" method="post" class="form segment">
            {% crispy form %}
            <input class="btn btn-success" type="submit" name="_save" value="Submit">
            <a class="btn btn-primary" href="/category/{{ object.name }}/edit/">Cancel</a>
        </form>

    </div>
{% endblock %}

templates/seals/map.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block body %}
    <div class="container">
        <header class="page-header clearfix">
            <div class="pull-left">
                <h3 class="page-title pull-left">
                    <a class="page-title" href="/national-government-agencies/">{% trans "National Government Agencies" %}</a>
                </h3>
                <h3 class="page-title">Local Government Units</h3>
            </div>
            {% if user.is_authenticated %}
                <div class="pull-right">
                        <a href="/new/" class="btn btn-primary"><i class="fa fa-plus"></i> Add new seal</a>
                        <a href="/category/new/" class="btn btn-primary"><i class="fa fa-plus"></i> Add new category</a>
                        <a href="/category/" class="btn btn-primary"><i class="fa fa-list"></i> View all categories</a>

                </div>
            {% endif %}
        </header>

        <div class="row">
            <div class="col-md-2">
                <div class="category-div">
                    <ul class="main-category-list">
                        {% for region in regions %}
                            <li class="category-list-item category-list-{{ region.id }}" data-category="{{ region.id }}">{{ region.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                {% for province in provinces %}
                    <div class="subcategory-popup-div subcategory-popup-{{ province.id }} hidden">
                        <ul class="main-category-list">
                            {% for lgu in object_list %}
                                {% if lgu.province == province %}
                                    <li><a href="/{{ lgu.name|slugify }}/">{{ lgu.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-3">
                {% for region in regions %}
                    <div class="category-popup-div category-popup-{{ region.id }} hidden">
                        <h2>{{ region.name }}</h2>
                        <ul class="main-category-list">
                            {% for province in provinces %}
                                {% if province.region == region %}
                                    <li><a class="subcategory-list-item" data-subcategory="{{ province.id }}">{{ province.name }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div id="svg-div">
                    <div class="visible-lg">
                        <svg class="seal-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="390" height="568">
                            <image class="map map390" x="0" y="0" width="390" height="568" xlink:href="/static/images/philippine-map.jpg"></image>

                            {% for region in regions %}
                                 <polygon class="category-map-highlight polygon-category-{{ region.id }}" data-category="{{ region.id }}"  points="{{ region.svg }}" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="1" opacity="0" transform="scale(.78)"></polygon>
                            {% endfor %}

                        </svg>
                    </div>

                    <div class="visible-md">
                        <svg class="seal-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="324" height="472">
                            <image class="map map324" x="0" y="0" width="324" height="472" xlink:href="/static/images/philippine-map.jpg"></image>

                            {% for region in regions %}
                                 <polygon class="category-map-highlight polygon-category-{{ region.id }}" data-category="{{ region.id }}"  points="{{ region.svg }}" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="1" opacity="0" transform="scale(.648)"></polygon>
                            {% endfor %}

                        </svg>
                    </div>

                    <div class="visible-sm">
                        <svg class="seal-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="250" height="364">
                            <image class="map map324" x="0" y="0" width="250" height="364" xlink:href="/static/images/philippine-map.jpg"></image>

                            {% for region in regions %}
                                 <polygon class="category-map-highlight polygon-category-{{ region.id }}" data-category="{{ region.id }}"  points="{{ region.svg }}" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="1" opacity="0" transform="scale(.5)"></polygon>
                            {% endfor %}

                        </svg>
                    </div>
                    <div class="visible-xs">
                        <svg class="seal-svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="250" height="364">
                            <image class="map map324" x="0" y="0" width="250" height="364" xlink:href="/static/images/philippine-map.jpg"></image>

                            {% for region in regions %}
                                 <polygon class="category-map-highlight polygon-category-{{ region.id }}" data-category="{{ region.id }}"  points="{{ region.svg }}" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="1" opacity="0" transform="scale(.5)"></polygon>
                            {% endfor %}

                        </svg>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_bottom %}
    <script type="text/javascript" src="{% static "js/jquery.svgdom.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.svg.min.js" %}"></script>

    <script type="text/javascript">
    //script for clicking region
    $(".category-list-item").click(function() {
        var id = $(this).data('category');
        $('.category-popup-div').addClass('hidden');
        $('.category-popup-'+id).removeClass('hidden');

        $(".category-list-item").removeClass('selected');
        $(this).addClass('selected');

        $(".category-map-highlight").each(function( index ) {
          this.classList.remove("selected");
        });

        $(".polygon-category-"+id).attr("class", "category-map-highlight polygon-category-" + id + " selected");
    });

    //script for hovering on province
    $(".subcategory-list-item").hover(function() {
        var id = $(this).data('subcategory');
        $('.subcategory-popup-div').addClass('hidden');
        $('.subcategory-popup-'+id).removeClass('hidden');
    });

    //script for selecting a region
    $(".category-list-item").click(function() {
        $(".main-category-list").addClass('selected');
    });

    //script for clicking on a region in the map
    $(".category-map-highlight").click(function() {
        var id = $(this).data('category');
        $(".main-category-list").addClass('selected');

        $('.category-popup-div').addClass('hidden');
        $('.category-popup-'+id).removeClass('hidden');
        $(".category-list-item").removeClass('selected');
        $('.category-list-'+id).addClass('selected');

        $(".category-map-highlight").each(function( index ) {
            this.classList.remove("selected");
        });
        this.classList.add("selected");
    });
    </script>
    <script type="text/javascript">

    </script>

{% endblock %}